sudo: required
services:
  - docker

before_install:
  - docker build -t stjepanpetrovic/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stjepanpetrovic/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-954566027091"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: "$AWS_SECRET_KEY"
